@startuml Gatochi_Estados

!theme blueprint

title Diagrama de Estados - Gatochi

[*] --> Sano

state "Sano" as Sano
state "Cansado" as Cansado
state "Hambriento" as Hambriento
state "Enfermo" as Enfermo
state "Necesita ir al baño" as Bano
state "Muerto" as Muerto

' ==========================
' ESTADO SANO
' ==========================

Sano --> Hambriento : comida = 0
Sano --> Cansado : energía = 0

' ==========================
' ESTADO HAMBRIENTO
' ==========================

Hambriento --> Muerto : 30 s sin comer
Hambriento --> Sano : come / comida = 1 o 2
Hambriento --> Cansado : energía = 0

' ==========================
' ESTADO CANSADO
' ==========================

Cansado --> Enfermo : después de 30 s
Cansado --> Sano : recupera energía
Cansado --> Hambriento : comida = 0

' ==========================
' ESTADO ENFERMO
' ==========================

Enfermo --> Sano : va al veterinario

' ==========================
' ESTADO NECESITA IR AL BAÑO
' ==========================

Bano --> Sano : usa el arenero
Bano --> Enfermo : no usa el arenero durante 30 s

' ==========================
' ESTADO MUERTO
' ==========================

Muerto --> Bano : revivir

@enduml